client_id = "e782b0b0778fa238926f5d95475225d7"
name = "Restocking Report Wilmington"
application_url = "https://restocking-report-wilmington.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://restocking-report-wilmington.onrender.com/webhooks/compliance"

[access_scopes]
scopes = "read_orders,read_inventory,read_products,read_locations"

[auth]
redirect_urls = [
  "https://restocking-report-wilmington.onrender.com/auth/callback",
  "https://restocking-report-wilmington.onrender.com/auth/shopify/callback"
]
