name = "Restocking Report"
handle = "restocking-report"

application_url = "https://restocking-report.onrender.com"
embedded = true

[auth]
redirect_urls = [
  "https://restocking-report.onrender.com/auth/callback",
  "https://restocking-report.onrender.com/auth/shopify/callback"
]

[build]
automatically_update_urls_on_dev = true
dev_store_url = "learning-express-dev-store.myshopify.com"

[access_scopes]
scopes = "read_inventory,read_locations,read_orders,read_products"
