client_id = "6a38bb4ae709a9300a1919428a55c900"
name = "Restocking Report Chatanooga"
application_url = "https://restocking-report-chatanooga.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://restocking-report.onrender.com/webhooks/compliance"

[access_scopes]
scopes = "read_orders,read_inventory,read_products,read_locations"

[auth]
redirect_urls = [
  "https://restocking-report-chatanooga.onrender.com/auth/callback",
  "https://restocking-report-chatanooga.onrender.com/auth/shopify/callback"
]
